# Generated by Django 3.0.3 on 2020-02-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('measure', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('sun', models.BooleanField()),
                ('mon', models.BooleanField()),
                ('tues', models.BooleanField()),
                ('wen', models.BooleanField()),
                ('thurs', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
            ],
        ),
    ]
