# Generated by Django 3.0.3 on 2020-02-10 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20200208_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
